
@url = http://localhost:80/api
@json = Content-Type: application/json




### show all users
get {{url}}/users

### get all posts   
get {{url}}/posts


### post something here
post {{url}}/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTUxMmQxZjM5ZGFkMjViMjY2MjZhYSIsImlhdCI6MTU3MTY5NjgwM30.ZxIA7q1fua3IqwgaXgkG9D8WxrPj58QzI9XzZOeZdkY
{{json}}

{
    "title" : "my first  post",
    "body" : "Hello World"
    
}

### register
post {{url}}/register
{{json}}

{
    "username" : "admin",
    "password" : "admin"
}

### login 
post {{url}}/login
{{json}}

{
    "username" : "user1",
    "password" : "123"
}




### Get person info
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTUwZmY1M2VjN2UxMjQxZjA4NGIwZiIsImlhdCI6MTU3MTA5OTA5NH0.W5X_PqiOp5Drcdpw_ww021YvFOkaVMItTXHAOypRu6I


###update person info
get {{url}}/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTUxMmQxZjM5ZGFkMjViMjY2MjZhYSIsImlhdCI6MTU3MTMzMTIzMH0.3JuXvE9JtEGOQjMIx2ifOdCOI-iGfEKFqyRyfc5MrT4
{{json}}

{
    "username" : "blablabla"
}


###update person password
get {{url}}/changePwd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTUxMmQxZjM5ZGFkMjViMjY2MjZhYSIsImlhdCI6MTU3MTY4Nzk4MH0.1ijgviB3NmjWeS1q6RIBqh6Ty1laRfPh06pdoDsEqTY
{{json}}

{
    "password" : "123"
}


###admin get all users' info.
get {{url}}/admin/profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTUxMmQxZjM5ZGFkMjViMjY2MjZhYSIsImlhdCI6MTU3MTEwMDI4Mn0.AJOldbgHrXHP5w0lmoG_aW1BVAyO1bd_pnsve6YzOKM
