
@url = http://localhost:80/api
@json = Content-Type: application/json




### show all users
get {{url}}/users

### get all posts   
get {{url}}/posts


### post something here
post {{url}}/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYjhhZjFkYTFiNDlkYWU0ZDRmZmRjOCIsImlhdCI6MTU3MjQ1MzIyM30.Pnrj12c9xJcY6qOK4eN8B27T_I9PK0pUYRDoU39eiZ0
{{json}}

{
    "title" : "",
    "body" : "",
    "region" : "north"
}

### register
post {{url}}/register
{{json}}

{
    "username" : "user1",
    "password" : "123",
    "email" : "user1@test.com"
}

### login 
post {{url}}/login
{{json}}

{
    "username" : "user1",
    "password" : "123"
}




### Get person info
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYjhhMzIzYjEwMDcwYTk4ZGVmZjZhZSIsImlhdCI6MTU3MjM4MTQ4Nn0.NBKsDD1vNd8OHHNGRcimlnQhukyUjyRVoRM26T2CDiA


###update person info
post {{url}}/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTUxMmQxZjM5ZGFkMjViMjY2MjZhYSIsImlhdCI6MTU3MTg0ODM3NX0.iQrXSHkdArCq0HmrlDNWTi7BWgkx5_LMkFXlT8zDRU0
{{json}}

{
    "region" : "blablabla"
}


###update person password
post {{url}}/changePwd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTUxMmQxZjM5ZGFkMjViMjY2MjZhYSIsImlhdCI6MTU3MTY4Nzk4MH0.1ijgviB3NmjWeS1q6RIBqh6Ty1laRfPh06pdoDsEqTY
{{json}}

{
    "password" : "123"
}


